//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carsport.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Carsport.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string AboutPoliciesTitle {
            get {
                return ResourceManager.GetString("AboutPoliciesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string AcceptDisplay {
            get {
                return ResourceManager.GetString("AcceptDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddNavBar {
            get {
                return ResourceManager.GetString("AddNavBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create route.
        /// </summary>
        public static string AddRouteMenuTitle {
            get {
                return ResourceManager.GetString("AddRouteMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My chats.
        /// </summary>
        public static string AllMyConversationTitle {
            get {
                return ResourceManager.GetString("AllMyConversationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bike Parking Lot.
        /// </summary>
        public static string BikeButton {
            get {
                return ResourceManager.GetString("BikeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bike Parking Lot.
        /// </summary>
        public static string BikeTitle {
            get {
                return ResourceManager.GetString("BikeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buses Schedules.
        /// </summary>
        public static string BusButton {
            get {
                return ResourceManager.GetString("BusButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buses Schedules.
        /// </summary>
        public static string BusMenuTitle {
            get {
                return ResourceManager.GetString("BusMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search schedule.
        /// </summary>
        public static string BusTitle {
            get {
                return ResourceManager.GetString("BusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonCreateRoute {
            get {
                return ResourceManager.GetString("ButtonCreateRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log-in.
        /// </summary>
        public static string ButtonLogin {
            get {
                return ResourceManager.GetString("ButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpool.
        /// </summary>
        public static string CarButton {
            get {
                return ResourceManager.GetString("CarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpool.
        /// </summary>
        public static string CarTitle {
            get {
                return ResourceManager.GetString("CarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap in the image to change..
        /// </summary>
        public static string ChangeImage {
            get {
                return ResourceManager.GetString("ChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassTitle {
            get {
                return ResourceManager.GetString("ChangePassTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePasswordSave {
            get {
                return ResourceManager.GetString("ChangePasswordSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chats.
        /// </summary>
        public static string ChatMenuTitle {
            get {
                return ResourceManager.GetString("ChatMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string ChatMessagesPlaceHolder {
            get {
                return ResourceManager.GetString("ChatMessagesPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a municipality of destiny..
        /// </summary>
        public static string CommuneDestinyValidation {
            get {
                return ResourceManager.GetString("CommuneDestinyValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a municipality of origin..
        /// </summary>
        public static string CommuneOriginValidation {
            get {
                return ResourceManager.GetString("CommuneOriginValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string ConfigurationMenuTitle {
            get {
                return ResourceManager.GetString("ConfigurationMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string ConfigurationTitle {
            get {
                return ResourceManager.GetString("ConfigurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove account.
        /// </summary>
        public static string ConfirmDeleteAccount {
            get {
                return ResourceManager.GetString("ConfirmDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete route.
        /// </summary>
        public static string ConfirmDeleteRoute {
            get {
                return ResourceManager.GetString("ConfirmDeleteRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password....
        /// </summary>
        public static string ConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("ConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ConfirmRegister {
            get {
                return ResourceManager.GetString("ConfirmRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select an destiny core..
        /// </summary>
        public static string CoreDestinyValidation {
            get {
                return ResourceManager.GetString("CoreDestinyValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select an origin core..
        /// </summary>
        public static string CoreOriginValidation {
            get {
                return ResourceManager.GetString("CoreOriginValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create route.
        /// </summary>
        public static string CreateRouteTitle {
            get {
                return ResourceManager.GetString("CreateRouteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string DashBoardTitle {
            get {
                return ResourceManager.GetString("DashBoardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the day of the route..
        /// </summary>
        public static string DateValidation {
            get {
                return ResourceManager.GetString("DateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently delete your account?.
        /// </summary>
        public static string DeleteAccountConfirmation {
            get {
                return ResourceManager.GetString("DeleteAccountConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this route?.
        /// </summary>
        public static string DeleteRouteConfirmation {
            get {
                return ResourceManager.GetString("DeleteRouteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a destination for the route..
        /// </summary>
        public static string DestinyCityValidation {
            get {
                return ResourceManager.GetString("DestinyCityValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a destiny station..
        /// </summary>
        public static string DestinyStationValidation {
            get {
                return ResourceManager.GetString("DestinyStationValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star a chat.
        /// </summary>
        public static string DetailRouteChatButton {
            get {
                return ResourceManager.GetString("DetailRouteChatButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat list.
        /// </summary>
        public static string DetailRouteChatListButton {
            get {
                return ResourceManager.GetString("DetailRouteChatListButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: .
        /// </summary>
        public static string DetailRouteDateLabel {
            get {
                return ResourceManager.GetString("DetailRouteDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string DetailRouteDescriptionLabel {
            get {
                return ResourceManager.GetString("DetailRouteDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destiny: .
        /// </summary>
        public static string DetailRouteDestinyLabel {
            get {
                return ResourceManager.GetString("DetailRouteDestinyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string DetailRouteEditLabel {
            get {
                return ResourceManager.GetString("DetailRouteEditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email: .
        /// </summary>
        public static string DetailRouteEmailLabel {
            get {
                return ResourceManager.GetString("DetailRouteEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin: .
        /// </summary>
        public static string DetailRouteOriginLabel {
            get {
                return ResourceManager.GetString("DetailRouteOriginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string DetailRouteRemoveButton {
            get {
                return ResourceManager.GetString("DetailRouteRemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of seats: .
        /// </summary>
        public static string DetailRouteSeatsLabel {
            get {
                return ResourceManager.GetString("DetailRouteSeatsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail route.
        /// </summary>
        public static string DetailRoutesTitle {
            get {
                return ResourceManager.GetString("DetailRoutesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route has been successfully edited..
        /// </summary>
        public static string EditMessages {
            get {
                return ResourceManager.GetString("EditMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit route.
        /// </summary>
        public static string EditRouteTitle {
            get {
                return ResourceManager.GetString("EditRouteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string EmailLoginLabel {
            get {
                return ResourceManager.GetString("EmailLoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter university mail....
        /// </summary>
        public static string EmailLoginPlaceHolder {
            get {
                return ResourceManager.GetString("EmailLoginPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your E-mail..
        /// </summary>
        public static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The origin station cannot be the same as the destination station..
        /// </summary>
        public static string EqualsStationValidation {
            get {
                return ResourceManager.GetString("EqualsStationValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string ForgotPasswodButtonBack {
            get {
                return ResourceManager.GetString("ForgotPasswodButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string ForgotPasswodTitle {
            get {
                return ResourceManager.GetString("ForgotPasswodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string ForgotPasswordButtonSend {
            get {
                return ResourceManager.GetString("ForgotPasswordButtonSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string ForgotPasswordLabel {
            get {
                return ResourceManager.GetString("ForgotPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string ForgotPasswordLink {
            get {
                return ResourceManager.GetString("ForgotPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A message will be sent to your email with your new password..
        /// </summary>
        public static string ForgotPasswordMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email UCA.
        /// </summary>
        public static string ForgotPasswordPlaceHolder {
            get {
                return ResourceManager.GetString("ForgotPasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From gallery.
        /// </summary>
        public static string FromGallery {
            get {
                return ResourceManager.GetString("FromGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At this time you can&apos;t connect to the server, try again later..
        /// </summary>
        public static string GetTokenWrong {
            get {
                return ResourceManager.GetString("GetTokenWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeNavBar {
            get {
                return ResourceManager.GetString("HomeNavBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where do you take the picture?.
        /// </summary>
        public static string ImageSource {
            get {
                return ResourceManager.GetString("ImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check you internet connection..
        /// </summary>
        public static string InternetError {
            get {
                return ResourceManager.GetString("InternetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep logged in.
        /// </summary>
        public static string KeepLogin {
            get {
                return ResourceManager.GetString("KeepLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Municipality.
        /// </summary>
        public static string LabelCommuneDestiny {
            get {
                return ResourceManager.GetString("LabelCommuneDestiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality of Origin.
        /// </summary>
        public static string LabelCommuneOrigin {
            get {
                return ResourceManager.GetString("LabelCommuneOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Core.
        /// </summary>
        public static string LabelCoreDestiny {
            get {
                return ResourceManager.GetString("LabelCoreDestiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin Core.
        /// </summary>
        public static string LabelCoreOrigin {
            get {
                return ResourceManager.GetString("LabelCoreOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string LabelDate {
            get {
                return ResourceManager.GetString("LabelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string LabelDescription {
            get {
                return ResourceManager.GetString("LabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City of destination.
        /// </summary>
        public static string LabelDestinyCity {
            get {
                return ResourceManager.GetString("LabelDestinyCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of places available.
        /// </summary>
        public static string LabelNumOfSeat {
            get {
                return ResourceManager.GetString("LabelNumOfSeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City of origin.
        /// </summary>
        public static string LabelOriginCity {
            get {
                return ResourceManager.GetString("LabelOriginCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station of destiny.
        /// </summary>
        public static string LabelStationDestiny {
            get {
                return ResourceManager.GetString("LabelStationDestiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station of origin.
        /// </summary>
        public static string LabelStationOrigin {
            get {
                return ResourceManager.GetString("LabelStationOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a destiny station.
        /// </summary>
        public static string LabelStationPickerDestiny {
            get {
                return ResourceManager.GetString("LabelStationPickerDestiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an origin station.
        /// </summary>
        public static string LabelStationPickerOrigin {
            get {
                return ResourceManager.GetString("LabelStationPickerOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        public static string LogOutTitle {
            get {
                return ResourceManager.GetString("LogOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My routes.
        /// </summary>
        public static string MyRouteMenuTitle {
            get {
                return ResourceManager.GetString("MyRouteMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new password....
        /// </summary>
        public static string NewPasswordPlaceholder {
            get {
                return ResourceManager.GetString("NewPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a new picture.
        /// </summary>
        public static string NewPicture {
            get {
                return ResourceManager.GetString("NewPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have an internet connection, please connect your internet..
        /// </summary>
        public static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string NotificationSearchPlaceHolder {
            get {
                return ResourceManager.GetString("NotificationSearchPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string NotificationTitle {
            get {
                return ResourceManager.GetString("NotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shedule does&apos;t found!.
        /// </summary>
        public static string NotShedule {
            get {
                return ResourceManager.GetString("NotShedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of available places must be greater than 0..
        /// </summary>
        public static string NumOfSeatMinValidation {
            get {
                return ResourceManager.GetString("NumOfSeatMinValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the number of available places..
        /// </summary>
        public static string NumOfSeatValidation {
            get {
                return ResourceManager.GetString("NumOfSeatValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok!.
        /// </summary>
        public static string OkMessage {
            get {
                return ResourceManager.GetString("OkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a source for the route..
        /// </summary>
        public static string OriginCityValidation {
            get {
                return ResourceManager.GetString("OriginCityValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city of origin cannot be the same as the city of destination..
        /// </summary>
        public static string OriginDestinyCityValidation {
            get {
                return ResourceManager.GetString("OriginDestinyCityValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select an origin station..
        /// </summary>
        public static string OriginStationValidation {
            get {
                return ResourceManager.GetString("OriginStationValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordLoginLabel {
            get {
                return ResourceManager.GetString("PasswordLoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password....
        /// </summary>
        public static string PasswordLoginPlaceHolder {
            get {
                return ResourceManager.GetString("PasswordLoginPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your password..
        /// </summary>
        public static string PasswordValidation {
            get {
                return ResourceManager.GetString("PasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a university.
        /// </summary>
        public static string PickerBycicles {
            get {
                return ResourceManager.GetString("PickerBycicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a destination municipality.
        /// </summary>
        public static string PickerCommuneDestiny {
            get {
                return ResourceManager.GetString("PickerCommuneDestiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a municipality of origin.
        /// </summary>
        public static string PickerCommuneOrigin {
            get {
                return ResourceManager.GetString("PickerCommuneOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an destiny core.
        /// </summary>
        public static string PickerCoreDestiny {
            get {
                return ResourceManager.GetString("PickerCoreDestiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an origin core.
        /// </summary>
        public static string PickerCoreOrigin {
            get {
                return ResourceManager.GetString("PickerCoreOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a city of destination.
        /// </summary>
        public static string PickerDestinyCity {
            get {
                return ResourceManager.GetString("PickerDestinyCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a line.
        /// </summary>
        public static string PickerLines {
            get {
                return ResourceManager.GetString("PickerLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a city of origin.
        /// </summary>
        public static string PickerOriginCity {
            get {
                return ResourceManager.GetString("PickerOriginCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policies.
        /// </summary>
        public static string PrivacityPoliciesTitle {
            get {
                return ResourceManager.GetString("PrivacityPoliciesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user was created successfully. Now you can enter with the email and the assigned password..
        /// </summary>
        public static string RegisterConfirmation {
            get {
                return ResourceManager.GetString("RegisterConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string RegisterEMail {
            get {
                return ResourceManager.GetString("RegisterEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your E-mail..
        /// </summary>
        public static string RegisterEMailError {
            get {
                return ResourceManager.GetString("RegisterEMailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your E-mail....
        /// </summary>
        public static string RegisterEmailPlaceHolder {
            get {
                return ResourceManager.GetString("RegisterEmailPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mail you just entered is not valid, make sure you are using your university mail..
        /// </summary>
        public static string RegisterEMailUcaError {
            get {
                return ResourceManager.GetString("RegisterEMailUcaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string RegisterFirstName {
            get {
                return ResourceManager.GetString("RegisterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your name..
        /// </summary>
        public static string RegisterFirstNameError {
            get {
                return ResourceManager.GetString("RegisterFirstNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name....
        /// </summary>
        public static string RegisterFirstNamePlaceholder {
            get {
                return ResourceManager.GetString("RegisterFirstNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string RegisterLastName {
            get {
                return ResourceManager.GetString("RegisterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your surname..
        /// </summary>
        public static string RegisterLastNameError {
            get {
                return ResourceManager.GetString("RegisterLastNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your lastname....
        /// </summary>
        public static string RegisterLastNamePlaceholder {
            get {
                return ResourceManager.GetString("RegisterLastNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string RegisterLink {
            get {
                return ResourceManager.GetString("RegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string RegisterPassword {
            get {
                return ResourceManager.GetString("RegisterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string RegisterPasswordConfirm {
            get {
                return ResourceManager.GetString("RegisterPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a confirm password..
        /// </summary>
        public static string RegisterPasswordConfirmError {
            get {
                return ResourceManager.GetString("RegisterPasswordConfirmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your confirm password....
        /// </summary>
        public static string RegisterPasswordConfirmPlaceHolder {
            get {
                return ResourceManager.GetString("RegisterPasswordConfirmPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password, minimum 6 characters..
        /// </summary>
        public static string RegisterPasswordError {
            get {
                return ResourceManager.GetString("RegisterPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password....
        /// </summary>
        public static string RegisterPasswordPlaceHolder {
            get {
                return ResourceManager.GetString("RegisterPasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string RegisterPasswordsNoMatch {
            get {
                return ResourceManager.GetString("RegisterPasswordsNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string RegisterSave {
            get {
                return ResourceManager.GetString("RegisterSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove account.
        /// </summary>
        public static string RemoveAccountButton {
            get {
                return ResourceManager.GetString("RemoveAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: .
        /// </summary>
        public static string RouteDateLabel {
            get {
                return ResourceManager.GetString("RouteDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destiny: .
        /// </summary>
        public static string RouteDestinyLabel {
            get {
                return ResourceManager.GetString("RouteDestinyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seats: .
        /// </summary>
        public static string RouteNumSeatsLabel {
            get {
                return ResourceManager.GetString("RouteNumSeatsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin: .
        /// </summary>
        public static string RouteOriginLabel {
            get {
                return ResourceManager.GetString("RouteOriginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car rutes.
        /// </summary>
        public static string RoutesTitle {
            get {
                return ResourceManager.GetString("RoutesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchRoute {
            get {
                return ResourceManager.GetString("SearchRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shedules.
        /// </summary>
        public static string SheduleTitle {
            get {
                return ResourceManager.GetString("SheduleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stations.
        /// </summary>
        public static string StationButton {
            get {
                return ResourceManager.GetString("StationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stations.
        /// </summary>
        public static string StationTittle {
            get {
                return ResourceManager.GetString("StationTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stand.
        /// </summary>
        public static string StopButton {
            get {
                return ResourceManager.GetString("StopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stands.
        /// </summary>
        public static string StopTittle {
            get {
                return ResourceManager.GetString("StopTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated password..
        /// </summary>
        public static string SuccessfulChangePassword {
            get {
                return ResourceManager.GetString("SuccessfulChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited route.
        /// </summary>
        public static string SuccessfulEdit {
            get {
                return ResourceManager.GetString("SuccessfulEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse schedule.
        /// </summary>
        public static string SwitchButton {
            get {
                return ResourceManager.GetString("SwitchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of uses.
        /// </summary>
        public static string TermsOfUsePoliciesTitle {
            get {
                return ResourceManager.GetString("TermsOfUsePoliciesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the time of the route..
        /// </summary>
        public static string TimeValidation {
            get {
                return ResourceManager.GetString("TimeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trains Schedules.
        /// </summary>
        public static string TrainButton {
            get {
                return ResourceManager.GetString("TrainButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shedule.
        /// </summary>
        public static string TrainSheduleTitle {
            get {
                return ResourceManager.GetString("TrainSheduleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trains Schedules.
        /// </summary>
        public static string TrainTitle {
            get {
                return ResourceManager.GetString("TrainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To see the changes restart the application..
        /// </summary>
        public static string UpdateProfileMessage {
            get {
                return ResourceManager.GetString("UpdateProfileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated.
        /// </summary>
        public static string UpdateProfileTitle {
            get {
                return ResourceManager.GetString("UpdateProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
